### ISSUE TITLE
Cannot install pycp2110

### ISSUE THREAD

**Issue by DittelHome** [philpagel/ut8803e#6]
Hi,
i want to test/use your ut8803e.py program.
i am not able to install pycp2110 on my linux mint version 22.
Whatever a try i get errors.

I have already tried:
**sudo apt install python3-pycp2110** 
 => no package found

**pip3 install r- requirements.txt** 
=> 
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

**apt install libhidapi-hidraw0**
=> successfully installed :)

Any hint for me ?

regards Klaus

**Comment by philpagel** [comment]
The problem with the pip install is that Debian (and probably other distros, too) now block pip-installing, not only globally but also into the user's local python environment. The rationale for that is that third party packages or differing version of system package may interfere with system tools that are written in python.
The solution is to create a virtual environment and install into that:

```
python3 -m venv .venv
source .venv/bin/activate
python3 -m pip install -r requirements.txt
```

That way, everything is neatly encapsulated and won't interfere with external things.
You need to remember to activate the venv before using the software – i.e. repeat the `source` part.

Regards Phil

**Comment by philpagel** [comment]
I just updated the repository in order to restructure it and turn this into a buildable and installable package and published it as a release. 
You should now be able to download one of the package files (`*.tgz` or `*.whl`) and install it with `pipx` which should be more convenient than messing around with venvs. You still need to install `libhidapi-hidraw0` yourself, but you did so already, anyway. You also need `pipx` itself.

**Comment by DittelHome** [comment]
Ok, i have choosen the pipx installation.

```
klaus@Klaus-Werkstatt:~/ut8803e$ ls
ut8803e-0.0.1.tar.gz
klaus@Klaus-Werkstatt:~/ut8803e$ pipx install ut8803e-0.0.1.tar.gz 
  installed package ut8803e 0.0.1, installed using Python 3.12.3
  These apps are now globally available
    - ut8803e
done! ✨ 🌟 ✨

```

libhidapi-hidraw0 is already installed

Device is ready:
```
[ 5282.580446] usb 2-2.4: USB disconnect, device number 8
[ 5285.318607] usb 2-2.4: new full-speed USB device number 10 using xhci_hcd
[ 5285.400890] usb 2-2.4: New USB device found, idVendor=10c4, idProduct=ea80, bcdDevice= 1.00
[ 5285.400906] usb 2-2.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 5285.400913] usb 2-2.4: Product: CP2110 HID USB-to-UART Bridge
[ 5285.400918] usb 2-2.4: Manufacturer: Silicon Laboratories
[ 5285.400923] usb 2-2.4: SerialNumber: 0067719A
[ 5285.419241] hid-generic 0003:10C4:EA80.0004: hiddev0,hidraw0: USB HID v1.11 Device [Silicon Laboratories CP2110 HID USB-to-UART Bridge] on usb-0000:00:14.0-2.4/input0

```

You should edit the usage section: Usage: ut8803e.py [OPTIONS] CMD:   => only ut8803e

Trying to get data:

```
klaus@Klaus-Werkstatt:~/ut8803e/src/ut8803e$ ut8803e log
Traceback (most recent call last):
  File "/home/klaus/.local/bin/ut8803e", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/klaus/.local/share/pipx/venvs/ut8803e/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klaus/.local/share/pipx/venvs/ut8803e/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/klaus/.local/share/pipx/venvs/ut8803e/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klaus/.local/share/pipx/venvs/ut8803e/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klaus/.local/share/pipx/venvs/ut8803e/lib/python3.12/site-packages/ut8803e/ut8803e.py", line 45, in main
    ut = ut8000(full=full, format=format)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klaus/.local/share/pipx/venvs/ut8803e/lib/python3.12/site-packages/ut8803e/ut8803e.py", line 295, in __init__
    self.iface = cp2110.CP2110Device()
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/klaus/.local/share/pipx/venvs/ut8803e/lib/python3.12/site-packages/cp2110/__init__.py", line 150, in __init__
    self.device = hid.Device(vid=vid, pid=pid)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/klaus/.local/share/pipx/venvs/ut8803e/lib/python3.12/site-packages/hid/__init__.py", line 174, in __init__
    raise HIDException('unable to open device')
hid.HIDException: unable to open device
klaus@Klaus-Werkstatt:~/ut8803e/src/ut8803e$ 


```

regards Klaus

**Comment by philpagel** [comment]
Hm. looks like cp2110 cannot connect. Please run python interactively and type this:

```{python}
import cp2110
dev = cp2110.CP2110Device()
```
Does that fail, too?

If so, please show me the output of `ls -la /dev/hid*`. Maybe you just need to be in a certain group to get access...

**Comment by DittelHome** [comment]
klaus@Klaus-Werkstatt:~/ut8803e/src/ut8803e$ python3
Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cp2110
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cp2110'
>>>

**Comment by philpagel** [comment]
Oh yes. for this to work, you need to install it into a venv...

Anyway – I suspect its a permission issue. maybe the hidraw device are owned by group `plugdev` or similar...
So let's inspect the `/dev/hid*`

**Comment by DittelHome** [comment]
```
klaus@Klaus-Werkstatt:~/ut8803e/src/ut8803e$ pipx list
venvs are in /home/klaus/.local/share/pipx/venvs
apps are exposed on your $PATH at /home/klaus/.local/bin
manual pages are exposed at /home/klaus/.local/share/man
   package ut8803e 0.0.1, installed using Python 3.12.3
    - ut8803e
klaus@Klaus-Werkstatt:~/ut8803e/src/ut8803e$ 
```

**Comment by DittelHome** [comment]
ok sorry, i forgot the display:

```
klaus@Klaus-Werkstatt:~/ut8803e/src/ut8803e$ ls -la /dev/hid*
crw------- 1 root root 241, 0 Okt 12 17:15 /dev/hidraw0
crw------- 1 root root 241, 1 Okt 12 15:16 /dev/hidraw1
crw------- 1 root root 241, 2 Okt 12 15:16 /dev/hidraw2

```
The uni-t is the hidraw0..

It think the:
ModuleNotFoundError: No module named 'cp2110'
is thw problem ..

**Comment by philpagel** [comment]
Maybe you can activate it like so:
```
source ~/.local/pipx/venvs/ut8803e/bin/activate 
```
But it looks like you need to be root to access it. Please try if that works. If it does, a suitable udev rule would solve this. However, I didn't take care of that so probably there is another package you need to install to get that rule.

**Comment by philpagel** [comment]
Here is a udev rule file – haven't tested it. Should actually be installed but apparently wasn't.
[](https://github.com/libusb/hidapi/blob/master/udev/69-hid.rules)
You could try installing it in `/etc/udev/riles.d`, uncomment line 33 and then re-plug the meter. If things go well, the device should now be owned by group `plugdev`.

**Comment by DittelHome** [comment]
Hi Phil,
**now it works, udev was the trick ..**
Thanks for your investigation !

You should add the folllwing to your installation instruction:

sudo chmod 777 /dev/hidraw0 for test purpose ..
Add a udev rule 50-usb-access.rules in /etc/udev/rules.d with this content:
KERNEL=="hidraw*", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea80", MODE="0666“ 
of course only for UT8803e
Use lsusb to ckeckout  Vendor and Product 
 
Restart of udev is not necessary, just replug device

PS:  You should change ./ut8803e.py unde "In a nutshell" to ut8803e

regards Klaus

**Comment by philpagel** [comment]
Excellent. Glad it works. Have fun with your actual measurement project.
